# Forecasting the Whole data with an Arrays

## Import the data and the librarires

In [1]:
import os
cwd = os.getcwd()
print(cwd)

chdir=os.chdir("D:\Folder D/New folder/WERK Student/EXCEL/")
print(chdir)

C:\Users\alihi
None


In [2]:
import numpy as np
import pandas as pd
from matplotlib import pyplot as plt
from statsmodels.tsa.stattools import adfuller
from statsmodels.tsa.seasonal import seasonal_decompose
from statsmodels.tsa.arima_model import ARIMA
from statsmodels.graphics.tsaplots import plot_acf, plot_pacf
from statsmodels.tsa.stattools import acf
import statsmodels.api as sm
import pmdarima as pm
plt.rcParams.update({'figure.figsize':(9,7), 'figure.dpi':120})
%matplotlib inline
from statsmodels.tsa.api import VAR
from statsmodels.tools.eval_measures import rmse, aic

<frozen importlib._bootstrap>:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
<frozen importlib._bootstrap>:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
<frozen importlib._bootstrap>:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
<frozen importlib._bootstrap>:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject


In [24]:
df = pd.read_csv('201102_DataSet Forecast_0.01.csv',
                 header=0, sep=';', parse_dates = ['transaction_date'], index_col = ['transaction_date'])

## Explorarty Data Analysis 

In [25]:
df.head()

warehouse_id  product_id  quantity
transaction_date                                    
1998-01-01                  10           4         3
1998-01-01                  10          11         3
1998-01-01                  10          12         3
1998-01-01                  10          14         2
1998-01-01                  10          16         3

In [26]:
df.info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 182883 entries, 1998-01-01 to 1998-12-30
Data columns (total 3 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   warehouse_id  182883 non-null  int64
 1   product_id    182883 non-null  int64
 2   quantity      182883 non-null  int64
dtypes: int64(3)
memory usage: 5.6 MB


## Apply forecasting on the Whole data

In [60]:
#a = df[['transaction_date']].values
b = pd.Series(df['warehouse_id'])
c = pd.Series(df['product_id'])
d = pd.Series(df['quantity'])
print(type(b))
print(type(c))
print(type(d))
print("Series to an array")
b_new = np.array(b.values.tolist())
print(type(b_new))
print(b_new)
c_new = np.array(c.values.tolist())
print(type(c_new))
print(c_new)
d_new = np.array(d.values.tolist())
print(type(d_new))
print(d_new)

<class 'pandas.core.series.Series'>
<class 'pandas.core.series.Series'>
<class 'pandas.core.series.Series'>
Series to an array
<class 'numpy.ndarray'>
[10 10 10 ... 10 10 10]
<class 'numpy.ndarray'>
[   4   11   12 ... 1542 1544 1549]
<class 'numpy.ndarray'>
[3 3 3 ... 4 2 3]


In [61]:
data1 = np.vstack([b, c,d])
print(data1)
print(data1.shape)
print(type(data1))

[[  10   10   10 ...   10   10   10]
 [   4   11   12 ... 1542 1544 1549]
 [   3    3    3 ...    4    2    3]]
(3, 182883)
<class 'numpy.ndarray'>


In [62]:
for p in range(5):
    for d in range(3):
        for q in range(5):
            order = (p,d,q)    
            try:
                model = ARIMA(data, order=(p,d,q))
                print("this works:{}, {}, {} ".format(p,d,q))
            except:
                print(order)
                print('reached exception')
                pass

(0, 0, 0)
reached exception
(0, 0, 1)
reached exception
(0, 0, 2)
reached exception
(0, 0, 3)
reached exception
(0, 0, 4)
reached exception
(0, 1, 0)
reached exception
(0, 1, 1)
reached exception
(0, 1, 2)
reached exception
(0, 1, 3)
reached exception
(0, 1, 4)
reached exception
(0, 2, 0)
reached exception
(0, 2, 1)
reached exception
(0, 2, 2)
reached exception
(0, 2, 3)
reached exception
(0, 2, 4)
reached exception
(1, 0, 0)
reached exception
(1, 0, 1)
reached exception
(1, 0, 2)
reached exception
(1, 0, 3)
reached exception
(1, 0, 4)
reached exception
(1, 1, 0)
reached exception
(1, 1, 1)
reached exception
(1, 1, 2)
reached exception
(1, 1, 3)
reached exception
(1, 1, 4)
reached exception
(1, 2, 0)
reached exception
(1, 2, 1)
reached exception
(1, 2, 2)
reached exception
(1, 2, 3)
reached exception
(1, 2, 4)
reached exception
(2, 0, 0)
reached exception
(2, 0, 1)
reached exception
(2, 0, 2)
reached exception
(2, 0, 3)
reached exception
(2, 0, 4)
reached exception
(2, 1, 0)
reached ex

In [57]:


#Best model:  ARIMA(5,0,0)(0,0,0)[0] intercept

import numpy as np
from statsmodels.tsa.arima_model import ARIMA

a = [1, 2]
b = [3, 4]
c = [5, 6]
d = [7, 8]

data = np.vstack([a, b, c, d])

print(data.shape)
print(data)

for p in range(4):
    for d in range(1):
        for q in range(2):
            order = (p,d,q)    
            try:
                model = ARIMA(data, order=(p,d,q))
                print("this works:{}, {}, {} ".format(p,d,q))
            except:
                print(order)
                print('reached exception')
                pass

(4, 2)
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
(0, 0, 0)
reached exception
(0, 0, 1)
reached exception
(1, 0, 0)
reached exception
(1, 0, 1)
reached exception
(2, 0, 0)
reached exception
(2, 0, 1)
reached exception
(3, 0, 0)
reached exception
(3, 0, 1)
reached exception


In [ ]:
data = np.dstack([a, b])
model = statsmodels.tsa.arima_model.ARIMA(data, order=(5,1,0))

In [53]:
#auto_arima() uses a stepwise approach to search multiple combinations of p,d,q parameters
#and chooses the best model that has the least AIC.

model = pm.auto_arima(data1, start_p=0, start_q=0,
                      test='adf',       # use adftest to find optimal 'd'
                      max_p=5, max_q=5, # maximum p and q
                      m=1,              # frequency of series
                      d=None,           # let model determine 'd'
                      seasonal=False,   # No Seasonality
                      start_P=0, 
                      D=0, 
                      trace=True,
                      error_action='ignore',  
                      suppress_warnings=True, 
                      stepwise=True)

print(model.summary())

Performing stepwise search to minimize aic
 ARIMA(0,0,0)(0,0,0)[0]             : AIC=8421369.698, Time=4.67 sec
 ARIMA(1,0,0)(0,0,0)[0]             : AIC=inf, Time=5.67 sec
 ARIMA(0,0,1)(0,0,0)[0]             : AIC=7718887.017, Time=50.91 sec
 ARIMA(1,0,1)(0,0,0)[0]             : AIC=5590446.121, Time=15.55 sec
 ARIMA(2,0,1)(0,0,0)[0]             : AIC=5590442.229, Time=21.28 sec
 ARIMA(2,0,0)(0,0,0)[0]             : AIC=inf, Time=9.36 sec
 ARIMA(3,0,1)(0,0,0)[0]             : AIC=5590447.621, Time=28.54 sec
 ARIMA(2,0,2)(0,0,0)[0]             : AIC=5590031.323, Time=82.00 sec
 ARIMA(1,0,2)(0,0,0)[0]             : AIC=5590444.326, Time=20.01 sec
 ARIMA(3,0,2)(0,0,0)[0]             : AIC=5590477.813, Time=155.91 sec
 ARIMA(2,0,3)(0,0,0)[0]             : AIC=inf, Time=189.35 sec
 ARIMA(1,0,3)(0,0,0)[0]             : AIC=5590444.589, Time=22.54 sec
 ARIMA(3,0,3)(0,0,0)[0]             : AIC=5590452.988, Time=235.71 sec
 ARIMA(2,0,2)(0,0,0)[0] intercept   : AIC=5590169.844, Time=216.65 sec
